<?php

use Illuminate\Database\Seeder;

class MarketingReportsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('marketing_reports')->delete();

        \DB::table('marketing_reports')->insert(array (
            0 =>
            array (
                'id' => 10,
                'employee_id' => 2,
                'area' => 'gazipur',
                'order' => 2500,
                'delivery' => 1300,
                'market' => 'projapoti',
                'comment' => 'regency coto borothakar problem',
                'productinfo' => NULL,
                'at' => '2021-01-19 00:00:00',
                'deleted_at' => '2021-01-18 18:26:22',
                'created_at' => '2021-01-18 18:21:40',
                'updated_at' => '2021-01-18 18:26:22',
            ),
            1 =>
            array (
                'id' => 11,
                'employee_id' => 10,
                'area' => 'singar',
                'order' => 1620,
                'delivery' => 910,
                'market' => 'carigram vanga bajer',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-01-31 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-01-31 12:07:27',
                'updated_at' => '2021-01-31 12:07:27',
            ),
            2 =>
            array (
                'id' => 12,
                'employee_id' => 15,
                'area' => 'mawna',
                'order' => 1080,
                'delivery' => 1080,
                'market' => 'valuka bazer',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-01 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-01 12:43:20',
                'updated_at' => '2021-02-01 12:43:20',
            ),
            3 =>
            array (
                'id' => 13,
                'employee_id' => 10,
                'area' => 'singar',
                'order' => 2165,
                'delivery' => 0,
                'market' => 'joymondop dholla',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-01 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-01 12:47:20',
                'updated_at' => '2021-02-01 12:47:20',
            ),
            4 =>
            array (
                'id' => 14,
                'employee_id' => 11,
                'area' => 'keranigonj',
                'order' => 1665,
                'delivery' => 0,
                'market' => 'Aganogor',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-01 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-01 12:49:57',
                'updated_at' => '2021-02-01 12:49:57',
            ),
            5 =>
            array (
                'id' => 15,
                'employee_id' => 16,
                'area' => 'keranigonj.....mode',
                'order' => 2400,
                'delivery' => 0,
                'market' => 'Abdullapur',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-01 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-01 12:52:30',
                'updated_at' => '2021-02-01 12:52:30',
            ),
            6 =>
            array (
                'id' => 16,
                'employee_id' => 5,
                'area' => 'dhaka-1',
                'order' => 0,
                'delivery' => 0,
                'market' => 'konabari',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-01 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-01 12:54:11',
                'updated_at' => '2021-02-01 12:54:11',
            ),
            7 =>
            array (
                'id' => 17,
                'employee_id' => 4,
                'area' => 'dhaka-2',
                'order' => 0,
                'delivery' => 0,
                'market' => 'murga para',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-01 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-01 12:55:32',
                'updated_at' => '2021-02-01 12:55:32',
            ),
            8 =>
            array (
                'id' => 18,
                'employee_id' => 13,
                'area' => 'sonargoen',
                'order' => 1400,
                'delivery' => 500,
                'market' => 'meghnar ghat',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-01 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-01 12:58:09',
                'updated_at' => '2021-02-01 12:58:09',
            ),
            9 =>
            array (
                'id' => 19,
                'employee_id' => 6,
                'area' => 'companigonj',
                'order' => 1750,
                'delivery' => 1440,
                'market' => 'kashipur',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-01 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-01 13:22:01',
                'updated_at' => '2021-02-01 13:22:01',
            ),
            10 =>
            array (
                'id' => 20,
                'employee_id' => 7,
                'area' => 'comilla',
                'order' => 2110,
                'delivery' => 1850,
                'market' => 'bisshorode',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-01 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-01 13:25:10',
                'updated_at' => '2021-02-01 13:25:10',
            ),
            11 =>
            array (
                'id' => 21,
                'employee_id' => 8,
                'area' => 'goripur',
                'order' => 2465,
                'delivery' => 950,
                'market' => 'chater',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-01 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-01 13:26:53',
                'updated_at' => '2021-02-01 13:26:53',
            ),
            12 =>
            array (
                'id' => 22,
                'employee_id' => 2,
                'area' => 'comilla',
                'order' => 0,
                'delivery' => 0,
                'market' => 'goripur',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-01 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-01 13:29:24',
                'updated_at' => '2021-02-01 13:29:24',
            ),
            13 =>
            array (
                'id' => 23,
                'employee_id' => 12,
                'area' => 'choumohuni',
                'order' => 845,
                'delivery' => 1170,
                'market' => 'gowalpur',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-01 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-01 13:32:18',
                'updated_at' => '2021-02-01 13:32:18',
            ),
            14 =>
            array (
                'id' => 24,
                'employee_id' => 9,
                'area' => 'dhaka',
                'order' => 0,
                'delivery' => 0,
                'market' => 'office e cilo',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-01 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-01 13:34:19',
                'updated_at' => '2021-02-01 13:34:19',
            ),
            15 =>
            array (
                'id' => 25,
                'employee_id' => 5,
                'area' => 'dhaka-1',
                'order' => 0,
                'delivery' => 0,
                'market' => 'Singar saver',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-02 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-02 10:55:26',
                'updated_at' => '2021-02-02 10:55:26',
            ),
            16 =>
            array (
                'id' => 26,
                'employee_id' => 15,
                'area' => 'mawna',
                'order' => 1540,
                'delivery' => 1540,
                'market' => 'joynno bazer',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-02 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-02 11:01:52',
                'updated_at' => '2021-02-02 11:01:52',
            ),
            17 =>
            array (
                'id' => 27,
                'employee_id' => 11,
                'area' => 'keranigonj',
                'order' => 1660,
                'delivery' => 630,
                'market' => 'shubadda bazer',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-02 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-02 11:03:35',
                'updated_at' => '2021-02-02 11:03:35',
            ),
            18 =>
            array (
                'id' => 28,
                'employee_id' => 10,
                'area' => 'singar',
                'order' => 2515,
                'delivery' => 1965,
                'market' => 'baira boimel',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-02 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-02 11:10:05',
                'updated_at' => '2021-02-02 11:10:05',
            ),
            19 =>
            array (
                'id' => 29,
                'employee_id' => 16,
                'area' => 'keranigonj.....model',
                'order' => 1700,
                'delivery' => 1200,
                'market' => 'ramerkanda bazer',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-02 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-02 11:13:35',
                'updated_at' => '2021-02-02 11:13:35',
            ),
            20 =>
            array (
                'id' => 30,
                'employee_id' => 4,
                'area' => 'dhaka-2',
                'order' => 0,
                'delivery' => 0,
                'market' => 'valanogor',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-02 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-02 11:15:24',
                'updated_at' => '2021-02-02 11:15:24',
            ),
            21 =>
            array (
                'id' => 31,
                'employee_id' => 13,
                'area' => 'sonargoen',
                'order' => 1025,
                'delivery' => 720,
                'market' => 'baroddi',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-02 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-02 11:17:06',
                'updated_at' => '2021-02-02 11:17:06',
            ),
            22 =>
            array (
                'id' => 32,
                'employee_id' => 2,
                'area' => 'comilla',
                'order' => 0,
                'delivery' => 0,
                'market' => 'goripur',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-02 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-02 11:18:22',
                'updated_at' => '2021-02-02 11:18:22',
            ),
            23 =>
            array (
                'id' => 33,
                'employee_id' => 7,
                'area' => 'comilla',
                'order' => 2749,
                'delivery' => 1442,
                'market' => 'borichong',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-02 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-02 11:20:19',
                'updated_at' => '2021-02-02 11:20:19',
            ),
            24 =>
            array (
                'id' => 34,
                'employee_id' => 6,
                'area' => 'companigonj',
                'order' => 870,
                'delivery' => 0,
                'market' => 'debidawer',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-02 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-02 11:23:44',
                'updated_at' => '2021-02-02 11:23:44',
            ),
            25 =>
            array (
                'id' => 35,
                'employee_id' => 8,
                'area' => 'goripur',
                'order' => 2335,
                'delivery' => 1620,
                'market' => 'gowalmari',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-02 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-02 11:25:30',
                'updated_at' => '2021-02-02 11:25:30',
            ),
            26 =>
            array (
                'id' => 36,
                'employee_id' => 9,
                'area' => 'dhaka',
                'order' => 0,
                'delivery' => 0,
                'market' => 'keranigonj',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-02 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-02 11:32:16',
                'updated_at' => '2021-02-02 11:32:16',
            ),
            27 =>
            array (
                'id' => 37,
                'employee_id' => 12,
                'area' => 'choumohuni',
                'order' => 0,
                'delivery' => 0,
                'market' => 'sonaymuri',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-02 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-02 17:49:23',
                'updated_at' => '2021-02-02 17:49:23',
            ),
            28 =>
            array (
                'id' => 38,
                'employee_id' => 5,
                'area' => 'dhaka-1',
                'order' => 0,
                'delivery' => 0,
                'market' => 'keranigonj',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-03 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-03 11:02:09',
                'updated_at' => '2021-02-03 11:02:09',
            ),
            29 =>
            array (
                'id' => 39,
                'employee_id' => 15,
                'area' => 'mawna',
                'order' => 1330,
                'delivery' => 0,
                'market' => 'monipur ,hotapara',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-03 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-03 11:13:51',
                'updated_at' => '2021-02-03 11:13:51',
            ),
            30 =>
            array (
                'id' => 40,
                'employee_id' => 11,
                'area' => 'keranigonj',
                'order' => 1630,
                'delivery' => 1450,
                'market' => 'teghuria bazer',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-03 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-03 11:15:42',
                'updated_at' => '2021-02-03 11:15:42',
            ),
            31 =>
            array (
                'id' => 41,
                'employee_id' => 10,
                'area' => 'singar',
                'order' => 2525,
                'delivery' => 1425,
                'market' => 'maniknogor',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-03 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-03 11:20:28',
                'updated_at' => '2021-02-03 11:20:28',
            ),
            32 =>
            array (
                'id' => 42,
                'employee_id' => 16,
                'area' => 'keranigonj.....model',
                'order' => 2600,
                'delivery' => 1800,
                'market' => 'kolatiya bazer',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-03 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-03 11:22:13',
                'updated_at' => '2021-02-03 11:22:13',
            ),
            33 =>
            array (
                'id' => 43,
                'employee_id' => 7,
                'area' => 'comilla',
                'order' => 2145,
                'delivery' => 2470,
                'market' => 'bisik market',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-03 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-03 11:27:16',
                'updated_at' => '2021-02-03 11:27:16',
            ),
            34 =>
            array (
                'id' => 44,
                'employee_id' => 6,
                'area' => 'companigonj',
                'order' => 2029,
                'delivery' => 870,
                'market' => 'racondrap',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-03 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-03 11:29:03',
                'updated_at' => '2021-02-03 11:29:03',
            ),
            35 =>
            array (
                'id' => 45,
                'employee_id' => 8,
                'area' => 'goripur',
                'order' => 2350,
                'delivery' => 1522,
                'market' => 'batakandi',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-03 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-03 11:32:00',
                'updated_at' => '2021-02-03 11:32:00',
            ),
            36 =>
            array (
                'id' => 46,
                'employee_id' => 2,
                'area' => 'comilla',
                'order' => 0,
                'delivery' => 0,
                'market' => 'companigonj',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-03 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-03 11:33:59',
                'updated_at' => '2021-02-03 11:33:59',
            ),
            37 =>
            array (
                'id' => 47,
                'employee_id' => 4,
                'area' => 'dhaka-2',
                'order' => 0,
                'delivery' => 0,
                'market' => 'murgapara',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-03 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-03 11:38:28',
                'updated_at' => '2021-02-03 11:38:28',
            ),
            38 =>
            array (
                'id' => 48,
                'employee_id' => 13,
                'area' => 'sonargoen',
                'order' => 2200,
                'delivery' => 0,
                'market' => 'chowrasta market',
                'comment' => 'gto kal ker delibari aj hobe',
                'productinfo' => NULL,
                'at' => '2021-02-03 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-03 11:41:33',
                'updated_at' => '2021-02-03 12:00:42',
            ),
            39 =>
            array (
                'id' => 49,
                'employee_id' => 9,
                'area' => 'dhaka',
                'order' => 0,
                'delivery' => 0,
                'market' => 'mirpur, newmarket',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-03 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-03 11:43:02',
                'updated_at' => '2021-02-03 11:48:48',
            ),
            40 =>
            array (
                'id' => 50,
                'employee_id' => 12,
                'area' => 'choumohuni',
                'order' => 950,
                'delivery' => 825,
                'market' => 'bojra amishapara',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-03 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-03 11:57:12',
                'updated_at' => '2021-02-03 11:57:41',
            ),
            41 =>
            array (
                'id' => 51,
                'employee_id' => 5,
                'area' => 'dhaka-1',
                'order' => 0,
                'delivery' => 0,
                'market' => 'keranigonj',
                'comment' => 'pick the phone',
                'productinfo' => NULL,
                'at' => '2021-02-04 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-04 10:54:36',
                'updated_at' => '2021-02-04 10:54:36',
            ),
            42 =>
            array (
                'id' => 52,
                'employee_id' => 15,
                'area' => 'mawna',
                'order' => 1180,
                'delivery' => 1620,
                'market' => 'gorgoria',
                'comment' => 'pick the phone',
                'productinfo' => NULL,
                'at' => '2021-02-04 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-04 11:01:36',
                'updated_at' => '2021-02-04 11:01:36',
            ),
            43 =>
            array (
                'id' => 53,
                'employee_id' => 4,
                'area' => 'dhaka-2',
                'order' => 0,
                'delivery' => 0,
                'market' => 'norsindi',
                'comment' => 'pick the phone',
                'productinfo' => NULL,
                'at' => '2021-02-04 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-04 11:14:18',
                'updated_at' => '2021-02-04 11:15:32',
            ),
            44 =>
            array (
                'id' => 54,
                'employee_id' => 13,
                'area' => NULL,
                'order' => 600,
                'delivery' => 1900,
                'market' => 'kaspur',
                'comment' => 'pick the phone',
                'productinfo' => NULL,
                'at' => '2021-02-04 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-04 11:17:32',
                'updated_at' => '2021-02-04 11:17:32',
            ),
            45 =>
            array (
                'id' => 55,
                'employee_id' => 10,
                'area' => 'singar',
                'order' => 2370,
                'delivery' => 660,
                'market' => 'khorarchor bazer',
                'comment' => 'pick the ph',
                'productinfo' => NULL,
                'at' => '2021-02-04 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-04 11:22:44',
                'updated_at' => '2021-02-04 11:22:44',
            ),
            46 =>
            array (
                'id' => 56,
                'employee_id' => 11,
                'area' => 'keranigonj',
                'order' => 2070,
                'delivery' => 1090,
                'market' => 'hasnabad',
                'comment' => 'pick the ph...........point e ace ,rejaul viyar sathe hasnabad jabe...aktu problem hoice',
                'productinfo' => NULL,
                'at' => '2021-02-04 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-04 11:28:52',
                'updated_at' => '2021-02-04 11:28:52',
            ),
            47 =>
            array (
                'id' => 57,
                'employee_id' => 16,
                'area' => 'keranigonj.....mode',
                'order' => 3100,
                'delivery' => 2010,
                'market' => 'kaligonj',
                'comment' => 'pick the ph',
                'productinfo' => NULL,
                'at' => '2021-02-04 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-04 11:34:37',
                'updated_at' => '2021-02-04 16:35:26',
            ),
            48 =>
            array (
                'id' => 58,
                'employee_id' => 7,
                'area' => 'comilla',
                'order' => 3260,
                'delivery' => 0,
                'market' => 'chandina',
                'comment' => 'pick the ph',
                'productinfo' => NULL,
                'at' => '2021-02-04 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-04 11:39:24',
                'updated_at' => '2021-02-04 11:39:24',
            ),
            49 =>
            array (
                'id' => 59,
                'employee_id' => 6,
                'area' => 'companigonj',
                'order' => 1450,
                'delivery' => 0,
                'market' => 'vangora',
                'comment' => 'pick the ph',
                'productinfo' => NULL,
                'at' => '2021-02-04 11:50:19',
                'deleted_at' => NULL,
                'created_at' => '2021-02-04 11:44:43',
                'updated_at' => '2021-02-04 11:44:43',
            ),
            50 =>
            array (
                'id' => 60,
                'employee_id' => 8,
                'area' => 'goripur',
                'order' => 3150,
                'delivery' => 1810,
                'market' => 'goripur bazer',
                'comment' => 'pick the ph',
                'productinfo' => NULL,
                'at' => '2021-02-04 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-04 11:45:52',
                'updated_at' => '2021-02-04 12:02:10',
            ),
            51 =>
            array (
                'id' => 61,
                'employee_id' => 2,
                'area' => 'comilla',
                'order' => 0,
                'delivery' => 0,
                'market' => 'feni',
                'comment' => 'pick the ph',
                'productinfo' => NULL,
                'at' => '2021-02-04 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-04 11:58:42',
                'updated_at' => '2021-02-04 11:58:42',
            ),
            52 =>
            array (
                'id' => 62,
                'employee_id' => 9,
                'area' => 'dhaka',
                'order' => 0,
                'delivery' => 0,
                'market' => 'kollanpur,',
                'comment' => 'pick the ph',
                'productinfo' => NULL,
                'at' => '2021-02-04 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-04 12:04:48',
                'updated_at' => '2021-02-04 12:13:02',
            ),
            53 =>
            array (
                'id' => 63,
                'employee_id' => 12,
                'area' => 'choumohuni',
                'order' => 0,
                'delivery' => 0,
                'market' => 'choumohuni bazer',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-04 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-04 16:38:59',
                'updated_at' => '2021-02-04 16:38:59',
            ),
            54 =>
            array (
                'id' => 64,
                'employee_id' => 2,
                'area' => 'comilla',
                'order' => 0,
                'delivery' => 0,
                'market' => 'Laksam',
                'comment' => 'pick the ph',
                'productinfo' => NULL,
                'at' => '2021-02-06 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-06 10:27:55',
                'updated_at' => '2021-02-06 10:27:55',
            ),
            55 =>
            array (
                'id' => 65,
                'employee_id' => 6,
                'area' => 'companigonj',
                'order' => 1945,
                'delivery' => 1444,
                'market' => 'banggora',
                'comment' => 'pick the ph',
                'productinfo' => NULL,
                'at' => '2021-02-06 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-06 10:35:26',
                'updated_at' => '2021-02-06 11:17:33',
            ),
            56 =>
            array (
                'id' => 66,
                'employee_id' => 7,
                'area' => 'comilla',
                'order' => 3462,
                'delivery' => 2400,
                'market' => 'ranir bazer',
                'comment' => 'pick the ph',
                'productinfo' => NULL,
                'at' => '2021-02-06 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-06 10:40:07',
                'updated_at' => '2021-02-06 11:18:17',
            ),
            57 =>
            array (
                'id' => 67,
                'employee_id' => 8,
                'area' => 'goripur',
                'order' => 1500,
                'delivery' => 3150,
                'market' => 'dautkandi',
                'comment' => 'pick the ph',
                'productinfo' => NULL,
                'at' => '2021-02-06 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-06 10:46:19',
                'updated_at' => '2021-02-06 10:46:19',
            ),
            58 =>
            array (
                'id' => 68,
                'employee_id' => 12,
                'area' => 'choumohuni',
                'order' => 2160,
                'delivery' => 1220,
                'market' => 'sambag samarhat',
                'comment' => 'pick the ph',
                'productinfo' => NULL,
                'at' => '2021-02-06 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-06 10:51:17',
                'updated_at' => '2021-02-06 10:51:17',
            ),
            59 =>
            array (
                'id' => 69,
                'employee_id' => 15,
                'area' => 'mawna',
                'order' => 1820,
                'delivery' => 0,
                'market' => 'shiripur',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-06 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-06 11:02:44',
                'updated_at' => '2021-02-06 11:02:44',
            ),
            60 =>
            array (
                'id' => 70,
                'employee_id' => 10,
                'area' => 'singar',
                'order' => 3570,
                'delivery' => 2100,
                'market' => 'shahorael',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-06 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-06 11:04:43',
                'updated_at' => '2021-02-06 11:14:29',
            ),
            61 =>
            array (
                'id' => 71,
                'employee_id' => 16,
                'area' => 'keranigonj.....model',
                'order' => 1600,
                'delivery' => 1770,
                'market' => 'chunkutiya',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-06 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-06 11:06:43',
                'updated_at' => '2021-02-06 11:06:43',
            ),
            62 =>
            array (
                'id' => 72,
                'employee_id' => 5,
                'area' => 'dhaka-1',
                'order' => 0,
                'delivery' => 0,
                'market' => 'keranigonj',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-06 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-06 11:19:41',
                'updated_at' => '2021-02-06 11:19:41',
            ),
            63 =>
            array (
                'id' => 73,
                'employee_id' => 4,
                'area' => 'dhaka-2',
                'order' => 0,
                'delivery' => 0,
                'market' => NULL,
                'comment' => 'office e ashce',
                'productinfo' => NULL,
                'at' => '2021-02-06 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-06 11:21:48',
                'updated_at' => '2021-02-06 11:25:47',
            ),
            64 =>
            array (
                'id' => 74,
                'employee_id' => 13,
                'area' => 'sonargoen',
                'order' => 2200,
                'delivery' => 1960,
                'market' => 'modonpur',
                'comment' => 'pick the ph',
                'productinfo' => NULL,
                'at' => '2021-02-06 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-06 11:25:03',
                'updated_at' => '2021-02-06 11:25:03',
            ),
            65 =>
            array (
                'id' => 75,
                'employee_id' => 9,
                'area' => 'dhaka',
                'order' => 0,
                'delivery' => 0,
                'market' => 'malibag, mouchak',
                'comment' => 'pick the ph',
                'productinfo' => NULL,
                'at' => '2021-02-06 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-06 11:28:53',
                'updated_at' => '2021-02-06 11:28:53',
            ),
            66 =>
            array (
                'id' => 76,
                'employee_id' => 2,
                'area' => 'comilla',
                'order' => 0,
                'delivery' => 0,
                'market' => 'companigonj',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-07 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-07 11:13:15',
                'updated_at' => '2021-02-07 11:13:15',
            ),
            67 =>
            array (
                'id' => 77,
                'employee_id' => 4,
                'area' => 'dhaka..2',
                'order' => 0,
                'delivery' => 0,
                'market' => 'velanogor',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-07 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-07 11:15:18',
                'updated_at' => '2021-02-07 11:15:18',
            ),
            68 =>
            array (
                'id' => 78,
                'employee_id' => 5,
                'area' => 'dhaka-1',
                'order' => 0,
                'delivery' => 0,
                'market' => 'gajipur',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-07 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-07 11:16:21',
                'updated_at' => '2021-02-07 11:16:21',
            ),
            69 =>
            array (
                'id' => 79,
                'employee_id' => 6,
                'area' => 'companigonj',
                'order' => 970,
                'delivery' => 1410,
                'market' => 'bishnopur',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-07 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-07 11:17:47',
                'updated_at' => '2021-02-07 11:17:47',
            ),
            70 =>
            array (
                'id' => 80,
                'employee_id' => 7,
                'area' => 'comilla',
                'order' => 1682,
                'delivery' => 1280,
                'market' => 'choddogaram',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-07 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-07 11:19:27',
                'updated_at' => '2021-02-07 11:19:27',
            ),
            71 =>
            array (
                'id' => 81,
                'employee_id' => 10,
                'area' => 'singar',
                'order' => 3570,
                'delivery' => 1700,
                'market' => 'charigaram',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-07 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-07 11:24:01',
                'updated_at' => '2021-02-07 11:24:01',
            ),
            72 =>
            array (
                'id' => 82,
                'employee_id' => 11,
                'area' => 'keranigonj',
                'order' => 0,
                'delivery' => 0,
                'market' => NULL,
                'comment' => 'Absent',
                'productinfo' => NULL,
                'at' => '2021-02-07 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-07 11:26:13',
                'updated_at' => '2021-02-07 11:26:13',
            ),
            73 =>
            array (
                'id' => 83,
                'employee_id' => 12,
                'area' => 'choumohuni',
                'order' => 1770,
                'delivery' => 2160,
                'market' => 'kajirhat',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-07 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-07 11:27:38',
                'updated_at' => '2021-02-07 11:27:38',
            ),
            74 =>
            array (
                'id' => 84,
                'employee_id' => 15,
                'area' => 'mawna',
                'order' => 1820,
                'delivery' => 1470,
                'market' => 'mawna bazer',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-07 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-07 11:28:38',
                'updated_at' => '2021-02-07 11:28:38',
            ),
            75 =>
            array (
                'id' => 85,
                'employee_id' => 13,
                'area' => 'sonargoen',
                'order' => 1160,
                'delivery' => 700,
                'market' => 'voberchor',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-07 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-07 11:30:14',
                'updated_at' => '2021-02-07 11:30:14',
            ),
            76 =>
            array (
                'id' => 86,
                'employee_id' => 16,
                'area' => 'keranigonj.....mode',
                'order' => 1600,
                'delivery' => 1000,
                'market' => 'laion market',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-07 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-07 11:31:11',
                'updated_at' => '2021-02-07 11:31:11',
            ),
            77 =>
            array (
                'id' => 87,
                'employee_id' => 9,
                'area' => 'dhaka',
                'order' => 0,
                'delivery' => 0,
                'market' => 'gulisthan',
                'comment' => NULL,
                'productinfo' => NULL,
                'at' => '2021-02-07 00:00:00',
                'deleted_at' => NULL,
                'created_at' => '2021-02-07 11:33:41',
                'updated_at' => '2021-02-07 11:33:41',
            ),
        ));


    }
}
